config/routes.rb
ControleManutencaoVenda::Application.routes.draw do
  resources :sales

  resources :services

  devise_for :users

  resources :cities
  resources :providers
  resources :customers
  resources :marks
  resources :category_products
  resources :products
  resources :dashboard

  root :to => 'dashboard#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
  validates_presence_of :nome, :message => " Digite o nome do Servico "
  validates_presence_of :valor, :message => " Digite o valor do Servico "
  attr_accessible :descricao, :nome, :valor
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.json
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= simple_form_for(@service) do |f| %>
  <%= f.error_notification %>

  <div class="row-fluid">
    <div class="span12">
      <div class="field">
        <%= f.input :nome, :input_html => { :type => 'text'}, label: 'Nome' %>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span6">
      <div class="field">
        <%= f.input :descricao, :input_html => { :type => 'text'}, label: 'Descrição' %>
      </div>
    </div>
    <div class="span6">
      <div class="field">
        <%= f.input :valor, :input_html => { :type => 'text'}, label: 'Valor' %>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="field">
    	<%= f.submit :class => 'btn btn-success' %>
	  </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
    $("#service_valor").maskMoney({symbol:"R$",decimal:",",thousands:"."})
</script>

app/views/services/edit.html.erb
<h1>Editar Serviço</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1>Listing services</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Valor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @services.each do |service| %>
  <tr>
    <td><%= service.nome %></td>
    <td><%= service.descricao %></td>
    <td><%= service.valor %></td>
    <td><%= link_to 'Show', service %></td>
    <td><%= link_to 'Edit', edit_service_path(service) %></td>
    <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Service', new_service_path, :class => 'btn btn-success' %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path, :class => 'btn btn-warning' %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @service.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @service.descricao %>
</p>

<p>
  <b>Valor:</b>
  <%= @service.valor %>
</p>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path, :class => 'btn btn-warning' %>