config/routes.rb
ControleManutencaoVenda::Application.routes.draw do
  resources :sales

  resources :services

  devise_for :users

  resources :cities
  resources :providers
  resources :customers
  resources :marks
  resources :category_products
  resources :products
  resources :dashboard

  root :to => 'dashboard#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :customer
  attr_accessible :clienteBairro, :clienteCep, :clienteCidade, :clienteEndereco, :clienteEstado, :clienteNome, :clienteNumero, :data, :valorDescontoVenda, :valorTotalProdutos, :valorTotalVenda
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale = Sale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sale }
    end
  end

  # GET /sales/new
  # GET /sales/new.json
  def new
    @sale = Sale.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sale }
    end
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(params[:sale])

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render json: @sale, status: :created, location: @sale }
      else
        format.html { render action: "new" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sales/1
  # PUT /sales/1.json
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :data %>
    <%= f.association :customer %>
    <%= f.input :clienteNome %>
    <%= f.input :clienteEndereco %>
    <%= f.input :clienteNumero %>
    <%= f.input :clienteBairro %>
    <%= f.input :clienteCidade %>
    <%= f.input :clienteEstado %>
    <%= f.input :clienteCep %>
    <%= f.input :valorTotalProdutos %>
    <%= f.input :valorDescontoVenda %>
    <%= f.input :valorTotalVenda %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Listing sales</h1>

<table>
  <tr>
    <th>Data</th>
    <th>Customer</th>
    <th>Clientenome</th>
    <th>Clienteendereco</th>
    <th>Clientenumero</th>
    <th>Clientebairro</th>
    <th>Clientecidade</th>
    <th>Clienteestado</th>
    <th>Clientecep</th>
    <th>Valortotalprodutos</th>
    <th>Valordescontovenda</th>
    <th>Valortotalvenda</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sales.each do |sale| %>
  <tr>
    <td><%= sale.data %></td>
    <td><%= sale.customer %></td>
    <td><%= sale.clienteNome %></td>
    <td><%= sale.clienteEndereco %></td>
    <td><%= sale.clienteNumero %></td>
    <td><%= sale.clienteBairro %></td>
    <td><%= sale.clienteCidade %></td>
    <td><%= sale.clienteEstado %></td>
    <td><%= sale.clienteCep %></td>
    <td><%= sale.valorTotalProdutos %></td>
    <td><%= sale.valorDescontoVenda %></td>
    <td><%= sale.valorTotalVenda %></td>
    <td><%= link_to 'Show', sale %></td>
    <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
    <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @sale.data %>
</p>

<p>
  <b>Customer:</b>
  <%= @sale.customer %>
</p>

<p>
  <b>Clientenome:</b>
  <%= @sale.clienteNome %>
</p>

<p>
  <b>Clienteendereco:</b>
  <%= @sale.clienteEndereco %>
</p>

<p>
  <b>Clientenumero:</b>
  <%= @sale.clienteNumero %>
</p>

<p>
  <b>Clientebairro:</b>
  <%= @sale.clienteBairro %>
</p>

<p>
  <b>Clientecidade:</b>
  <%= @sale.clienteCidade %>
</p>

<p>
  <b>Clienteestado:</b>
  <%= @sale.clienteEstado %>
</p>

<p>
  <b>Clientecep:</b>
  <%= @sale.clienteCep %>
</p>

<p>
  <b>Valortotalprodutos:</b>
  <%= @sale.valorTotalProdutos %>
</p>

<p>
  <b>Valordescontovenda:</b>
  <%= @sale.valorDescontoVenda %>
</p>

<p>
  <b>Valortotalvenda:</b>
  <%= @sale.valorTotalVenda %>
</p>


<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>