config/routes.rb
ControleManutencaoVenda::Application.routes.draw do
  resources :sales

  resources :services

  devise_for :users

  resources :cities
  resources :providers
  resources :customers
  resources :marks
  resources :category_products
  resources :products
  resources :dashboard

  root :to => 'dashboard#index'

end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
  validates_presence_of :nome, :message => " Digite o nome da Categoria "
  attr_accessible :nome
end

app/controllers/category_products_controller.rb
class CategoryProductsController < ApplicationController
  # GET /category_products
  # GET /category_products.json
  def index
    @category_products = CategoryProduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @category_products }
    end
  end

  # GET /category_products/1
  # GET /category_products/1.json
  def show
    @category_product = CategoryProduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category_product }
    end
  end

  # GET /category_products/new
  # GET /category_products/new.json
  def new
    @category_product = CategoryProduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category_product }
    end
  end

  # GET /category_products/1/edit
  def edit
    @category_product = CategoryProduct.find(params[:id])
  end

  # POST /category_products
  # POST /category_products.json
  def create
    @category_product = CategoryProduct.new(params[:category_product])

    respond_to do |format|
      if @category_product.save
        format.html { redirect_to @category_product, notice: 'Category product was successfully created.' }
        format.json { render json: @category_product, status: :created, location: @category_product }
      else
        format.html { render action: "new" }
        format.json { render json: @category_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /category_products/1
  # PUT /category_products/1.json
  def update
    @category_product = CategoryProduct.find(params[:id])

    respond_to do |format|
      if @category_product.update_attributes(params[:category_product])
        format.html { redirect_to @category_product, notice: 'Category product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_products/1
  # DELETE /category_products/1.json
  def destroy
    @category_product = CategoryProduct.find(params[:id])
    @category_product.destroy

    respond_to do |format|
      format.html { redirect_to category_products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/category_products_helper.rb
module CategoryProductsHelper
end

app/views/category_products/_form.html.erb
<%= simple_form_for(@category_product) do |f| %>
<div class="row-fluid">
	<div class="span12">
		<%= f.input :nome, label: 'Nome' %>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<%= f.submit :class => 'btn btn-success'%>
	</div>
</div>
<% end %>

app/views/category_products/edit.html.erb
<h1>Editing category_product</h1>

<%= render 'form' %>

<div class="actions">
<%= link_to 'Show', @category_product %> |
<%= link_to 'Voltar', category_products_path, :class => 'btn btn-warning'  %>
</div>

app/views/category_products/index.html.erb
<h1>Categorias</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @category_products.each do |category_product| %>
  <tr>
    <td><%= category_product.nome %></td>
    <td><%= link_to 'Show', category_product %></td>
    <td><%= link_to 'Edit', edit_category_product_path(category_product) %></td>
    <td><%= link_to 'Destroy', category_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova Categoria', new_category_product_path, :class => 'btn btn-success'  %>

app/views/category_products/new.html.erb
<h1>Nova Categoria</h1>

<%= render 'form' %>

<div class="actions">
<%= link_to 'Voltar', category_products_path, :class => 'btn btn-warning'  %>
</div>

app/views/category_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @category_product.nome %>
</p>


<%= link_to 'Edit', edit_category_product_path(@category_product) %> |
<%= link_to 'Voltar', category_products_path, :class => 'btn btn-warning' %>